mcq_bank = {
    "Math": [
        {"question": "What is 2 + 2?", "options": ["3", "4", "5", "6"], "answer": "4"},
        {"question": "What is 10 / 2?", "options": ["2", "5", "10", "20"], "answer": "5"},
        {"question": "What is 3 * 3?", "options": ["6", "9", "12", "15"], "answer": "9"},
        {"question": "What is 7 - 3?", "options": ["3", "4", "5", "6"], "answer": "4"},
        {"question": "What is 5 + 5?", "options": ["8", "9", "10", "11"], "answer": "10"},
        {"question": "Square of 5 is?", "options": ["20", "25", "15", "30"], "answer": "25"},
        {"question": "What is 100 ÷ 10?", "options": ["5", "10", "15", "20"], "answer": "10"},
        {"question": "What is 8 × 7?", "options": ["56", "64", "49", "48"], "answer": "56"},
        {"question": "Cube of 2 is?", "options": ["4", "6", "8", "10"], "answer": "8"},
        {"question": "What is 9 + 6?", "options": ["14", "15", "16", "17"], "answer": "15"},
        {"question": "What is 15 - 5?", "options": ["10", "5", "8", "12"], "answer": "10"},
        {"question": "What is 6 * 6?", "options": ["36", "30", "42", "40"], "answer": "36"},
        {"question": "What is 81 ÷ 9?", "options": ["7", "8", "9", "10"], "answer": "9"},
        {"question": "What is 25 + 25?", "options": ["50", "45", "55", "60"], "answer": "50"},
        {"question": "Square root of 49?", "options": ["6", "7", "8", "9"], "answer": "7"},
    ],
    "Science": [
        {"question": "What is H2O?", "options": ["Water", "Oxygen", "Hydrogen", "Helium"], "answer": "Water"},
        {"question": "What planet is known as the Red Planet?", "options": ["Earth", "Mars", "Jupiter", "Venus"], "answer": "Mars"},
        {"question": "What gas do plants absorb?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"], "answer": "Carbon Dioxide"},
        {"question": "What is the center of an atom called?", "options": ["Electron", "Proton", "Nucleus", "Neutron"], "answer": "Nucleus"},
        {"question": "Which organ pumps blood?", "options": ["Liver", "Brain", "Heart", "Lungs"], "answer": "Heart"},
        {"question": "Which vitamin is produced by sunlight?", "options": ["A", "B", "C", "D"], "answer": "D"},
        {"question": "What force pulls objects to Earth?", "options": ["Magnetism", "Gravity", "Friction", "Electricity"], "answer": "Gravity"},
        {"question": "Which gas do humans exhale?", "options": ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], "answer": "Carbon Dioxide"},
        {"question": "Boiling point of water?", "options": ["90°C", "100°C", "110°C", "120°C"], "answer": "100°C"},
        {"question": "What part of plant makes food?", "options": ["Root", "Stem", "Leaves", "Flower"], "answer": "Leaves"},
        {"question": "Sun is a?", "options": ["Planet", "Star", "Moon", "Comet"], "answer": "Star"},
        {"question": "Which metal is liquid at room temp?", "options": ["Iron", "Mercury", "Gold", "Silver"], "answer": "Mercury"},
        {"question": "Basic unit of life?", "options": ["Atom", "Molecule", "Cell", "Tissue"], "answer": "Cell"},
        {"question": "Which organ helps in breathing?", "options": ["Liver", "Heart", "Lungs", "Kidney"], "answer": "Lungs"},
        {"question": "Electric bulb was invented by?", "options": ["Edison", "Newton", "Einstein", "Faraday"], "answer": "Edison"},
    ],
    "Java": [
        {"question": "Which keyword is used to inherit a class in Java?", "options": ["extends", "implements", "inherits", "super"], "answer": "extends"},
        {"question": "What is the size of int in Java?", "options": ["4 bytes", "2 bytes", "8 bytes", "1 byte"], "answer": "4 bytes"},
        {"question": "Which method is the entry point of Java program?", "options": ["start()", "main()", "run()", "init()"], "answer": "main()"},
        {"question": "Java is platform-?", "options": ["Independent", "Dependent", "Both", "None"], "answer": "Independent"},
        {"question": "Which company developed Java?", "options": ["Microsoft", "Oracle", "Sun Microsystems", "IBM"], "answer": "Sun Microsystems"},
        {"question": "Which is not a Java keyword?", "options": ["class", "int", "goto", "define"], "answer": "define"},
        {"question": "Which access specifier is most restrictive?", "options": ["public", "private", "protected", "default"], "answer": "private"},
        {"question": "Java supports?", "options": ["Multiple inheritance with classes", "Single inheritance", "Multiple inheritance with interfaces", "No inheritance"], "answer": "Multiple inheritance with interfaces"},
        {"question": "Which of these is a loop in Java?", "options": ["repeat", "foreach", "loop", "for"], "answer": "for"},
        {"question": "What is bytecode in Java?", "options": ["Machine code", "Intermediate code", "Assembly code", "Binary code"], "answer": "Intermediate code"},
        {"question": "JVM stands for?", "options": ["Java Virtual Machine", "Java Verified Machine", "Just Virtual Machine", "Java Vendor Module"], "answer": "Java Virtual Machine"},
        {"question": "Which class is the superclass of all classes?", "options": ["String", "Object", "Class", "System"], "answer": "Object"},
        {"question": "Which operator is used to compare values?", "options": ["=", "==", "!=", "==="], "answer": "=="},
        {"question": "Which exception is unchecked?", "options": ["IOException", "SQLException", "NullPointerException", "FileNotFoundException"], "answer": "NullPointerException"},
        {"question": "Which loop is guaranteed to run at least once?", "options": ["for", "while", "do-while", "foreach"], "answer": "do-while"},
    ],
    "NoSQL": [
        {"question": "Which of these is a NoSQL database?", "options": ["MySQL", "MongoDB", "PostgreSQL", "SQLite"], "answer": "MongoDB"},
        {"question": "NoSQL databases are best suited for?", "options": ["Structured Data", "Unstructured Data", "Relational Data", "None of these"], "answer": "Unstructured Data"},
        {"question": "MongoDB stores data in?", "options": ["Tables", "Rows", "Documents", "Schemas"], "answer": "Documents"},
        {"question": "Which is not a type of NoSQL DB?", "options": ["Document", "Graph", "Key-Value", "Table"], "answer": "Table"},
        {"question": "Cassandra is a?", "options": ["Key-value DB", "Column-family store", "Graph DB", "Relational DB"], "answer": "Column-family store"},
        {"question": "NoSQL is?", "options": ["Schema-less", "Table-based", "Relational", "Fixed-schema"], "answer": "Schema-less"},
        {"question": "CAP theorem includes?", "options": ["Consistency, Availability, Partition tolerance", "Cache, Access, Performance", "Control, Analysis, Processing", "None"], "answer": "Consistency, Availability, Partition tolerance"},
        {"question": "What is sharding?", "options": ["Data backup", "Data compression", "Data distribution", "Data deletion"], "answer": "Data distribution"},
        {"question": "Redis is a?", "options": ["Document DB", "Graph DB", "Key-Value store", "Column store"], "answer": "Key-Value store"},
        {"question": "Which is not a NoSQL DB?", "options": ["Cassandra", "CouchDB", "Neo4j", "Oracle"], "answer": "Oracle"},
        {"question": "What is BSON?", "options": ["Binary JSON", "Basic SQL Object Notation", "Binary Syntax Object Notation", "None"], "answer": "Binary JSON"},
        {"question": "Neo4j is a?", "options": ["Document DB", "Key-Value DB", "Graph DB", "Relational DB"], "answer": "Graph DB"},
        {"question": "Which DB is suitable for relationships?", "options": ["Neo4j", "MongoDB", "Redis", "Cassandra"], "answer": "Neo4j"},
        {"question": "Data in NoSQL is stored as?", "options": ["Tables", "Rows", "Collections", "Documents"], "answer": "Documents"},
        {"question": "Which NoSQL DB is good for caching?", "options": ["MongoDB", "Redis", "Neo4j", "Cassandra"], "answer": "Redis"},
    ]
}
